services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  express:
    image: node:19
    command: bash -c "npm install && npm run start:dev"
    working_dir: /src
    ports:
      - 8081:8081
    volumes:
      - ./backend:/src
    environment:
      MONGO_URI: mongodb://root:example@mongo:27017/
      PORT: 8081